### ISSUE TITLE
Not able to login after initial install

### ISSUE THREAD

**Issue by Beverdam** [rackerlabs/scantron#105]
After running the master ansible-playbook and browsing to the url of the mastermachine, I get greeted by a Django login page. I set a password with a length of 12 characters in master/scantron_secrets.json. However, I am not able to login using that password icw the user scantron. Any hints on how to troubleshoot this?

**Comment by derpadoo** [comment]
Hi @Beverdam - Which user are you trying to log in as?  The `admin` user is specified in the `master/scantron_secrets.json` file.  If you need to change/update the Django password for a user, you can do that after SSHing into Master:

```bash
cd /home/scantron/master
source .venv/bin/activate  # or use the "av" alias
python3 manage.py changepassword scantron
```

Let me know if that still doesn't help.

**Comment by derpadoo** [comment]
This may be a bug.  Just deployed and it didn't accept my password set in `master/scantron_secrets.json`.  I had to update it using the commands above.

**Comment by derpadoo** [comment]
@Beverdam out of curiosity, did the password contain an exclamation point (`!`)?

**Comment by Beverdam** [comment]
Haven’t had time to deploy it again. Password did not contain an exclamation (!) mark. I will try to do some testing tomorrow night.

**Comment by derpadoo** [comment]
Just pushed a big update to master tonight.  If possible, re-checkout the repo and try a fresh install.

**Comment by Beverdam** [comment]
Did a fresh install, but getting a different error this time around when running the master playbook:

TASK [master : Enable uWSGI, and restart it. name=uwsgi.service, state=restarted, enabled=True] ******************
fatal: [192.168.2.158]: FAILED! => {
    "changed": false
}

MSG:

Unable to start service uwsgi.service: Warning: The unit file, source configuration file or drop-ins of uwsgi.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for uwsgi.service failed because the control process exited with error code.
See "systemctl status uwsgi.service" and "journalctl -xe" for details.

**Comment by derpadoo** [comment]
can you run the master portion of the playbook with `-vv`?

```bash
ansible-playbook master.yml -u root -vv --tags master
```

**Comment by Beverdam** [comment]
Did a complete reinstall with the latest commits on a fresh Ubuntu 18.04 machine. Installer script now runs fine. Once the ansible script finishes running and I go to http://serveradres I get redirected to https://serveradres/login/?next=/ 

I believe I need to login in order to setup a user that can manage the server, correct? I still do not have credentials to login after the default setup. 

I did not supply any Django keys, as the documentation did not mention it to be mandatory.

I also tried to run python3 manage.py changepassword admin, which gave the following error

```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import django  # noqa
ModuleNotFoundError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

```
How to proceed?

**Comment by Beverdam** [comment]
I ran pip3 install django and retried the python3 manage.py changepassword admin

python3 manage.py changepassword
Traceback (most recent call last):
  File "/home/wieger/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 204, in fetch_command
    app_name = commands[subcommand]
KeyError: 'changepassword'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/user/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 211, in fetch_command
    settings.INSTALLED_APPS
  File "/home/user/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/user/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/user/.local/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config.settings.production'

**Comment by Beverdam** [comment]
So, it seems that the Django password is mandatory. After that you can login with the password you set and the user admin. From there you can add additional users. I'll see if I can clean that part of the documentation up and created a pull request in the coming days.

**Comment by derpadoo** [comment]
1) It didn't look like you had the Python virtual environment enabled:

```bash
cd /home/scantron/master
source .venv/bin/activate  # or use the "av" alias
python3 manage.py changepassword <USER>
```

2) A password to log into the web GUI is required.

3) Feel free to submit a PR with any clarifications for the README / installation!
