### ISSUE TITLE
Investigate compiled standalone agent binary

### ISSUE THREAD

**Issue by derpadoo** [rackerlabs/scantron#144]
* https://nuitka.net/pages/overview.html

* https://github.com/Nuitka/Nuitka

**Comment by derpadoo** [comment]
```bash
virtualenv -p python3.6 .venv
source .venv/bin/activate
pip install -r requirements.txt
pip install -U nuitka
cd agent/
python -m nuitka --follow-imports agent.py
./agent.bin
```

**Comment by maaaaz** [comment]
Or at least a `pyinstaller --onefile` standalone.

**Comment by derpadoo** [comment]
I think I looked into that...it was just kind of kludgy.  Leaning more towards a compiled agent now, like something written in golang.

**Comment by derpadoo** [comment]
@maaaaz Revisited using `pyinstaller --onefile` after consolidating `agent.py` into 1 file without dependencies (https://github.com/rackerlabs/scantron/releases/tag/v1.31) and it looks promising.  Comes in at 5.5 MB.

**Comment by maaaaz** [comment]
Great, 5.5 MB is a tiny size, mostly used by the embedded Python interpreter. 
`pyinstaller` works great with dependency-less scripts.

**Comment by derpadoo** [comment]
Added standalone binary in https://github.com/rackerlabs/scantron/pull/224
