### ISSUE TITLE
Last update for Site model

### ISSUE THREAD

**Issue by jacekjaros** [rackerlabs/scantron#281]
is this possible to add information of time when site was updated?

i use script to update ip addresses in list. i know that i can check http code after update however i need to expose  information about last success update to other systems related to scantron however this not look as best approach.

my goal is to have easy way to get information if sites stop to be updated.

**Comment by derpadoo** [comment]
Hi @jacekjaros - appreciate the suggestion!  This is definitely possible and should be quick to implement.

1) Add `created = models.DateTimeField(auto_now_add=True)` to Site and any other relevant models

2) Add `last_updated = models.DateTimeField(auto_now=True, verbose_name="Last Updated")` to Site and any other relevant models

3) Add fields to API serializers (https://github.com/rackerlabs/scantron/blob/master/console/django_scantron/api/serializers.py) and make them read only.

**Comment by derpadoo** [comment]
Hi @jacekjaros - just merged PR https://github.com/rackerlabs/scantron/pull/282 into master.

Release notes: https://github.com/rackerlabs/scantron/releases/tag/v1.47.0

**Comment by derpadoo** [comment]
I'll keep this open for a few days if you have any other questions or issues.
