### ISSUE TITLE
how to open issue?

### ISSUE THREAD

**Issue by jacekjaros** [rackerlabs/scantron#284]
Hi,

Project was moved to https://github.com/opsdisk/scantron however I'm unable to open new issue there. Should i open it in  rackerlabs/scantron?

best regards,
Jacek

**Comment by opsdisk** [comment]
Hi @jacekjaros 

My bad, just enabled issues for https://github.com/opsdisk/scantron

**Comment by jacekjaros** [comment]
thanks @opsdisk
