### ISSUE TITLE
Reoccurence required for scan?

### ISSUE THREAD

**Issue by opsdisk** [rackerlabs/scantron#32]
"if you DONT schedule a recurrence, it will fail" - need to investigate some more

**Comment by derpadoo** [comment]
Ideally enforced by form.

Jam in today's date here?  https://github.com/rackerlabs/scantron/blob/master/master/scan_scheduler.py#L77

**Comment by derpadoo** [comment]
https://github.com/rackerlabs/scantron/pull/61 should have fixed this.  Allows for setting a single, non-recurring scan to occur the day it is submitted (today).
