### ISSUE TITLE
nmap_to_csv.py isn't moving .nmap and .gnmap files

### ISSUE THREAD

**Issue by derpadoo** [rackerlabs/scantron#36]

**Comment by 0xtavian** [comment]
find a way to incorporate https://github.com/maaaaz/nmaptocsv/blob/master/nmaptocsv.py
you'll thank yourself later i promise.

**Comment by 0xtavian** [comment]
find a way to incorporate https://github.com/maaaaz/nmaptocsv/blob/master/nmaptocsv.py you'll thank yourself later i promise.

**Comment by derpadoo** [comment]
Script is working as intended.
