### ISSUE TITLE
Agents arent provided API key by default

### ISSUE THREAD

**Issue by 0xtavian** [rackerlabs/scantron#39]
The ansible workload should add the APIs keys to every agent. This prevents having to manually login to all agents to add them yourself.

**Comment by derpadoo** [comment]
@0xtavian Let me know how it works for you.  

1) Update the branch

```bash
git clone https://github.com/rackerlabs/scantron.git
git checkout issue-39-prefill-agent-api-key
```

2) Switch `utilize_static_api_token_across_agents` to `True` in `scantron/ansible-playbooks/group_vars/all `
3) Run the master playbook first (I need to update README info), so the API key can be generated.  It dumps it to `group_vars/static_api_key`, so make sure that file is created.
4) Run the agent playbook, which fills an `agent_config.json.j2` template with the API key found in `group_vars/static_api_key`.

**Comment by derpadoo** [comment]
Added logic to randomize the `user_agent` in `agent_config.json` to avoid scan agent name collisions.  So now, you'd never need to log into the agents to update anything.  You'd still have to add the user on Master though since that's how scheduled scans are filtered.  Does that seem reasonable?
