### ISSUE TITLE
initial_setup.sh requires root and shouldnt 

### ISSUE THREAD

**Issue by 0xtavian** [rackerlabs/scantron#40]
https://github.com/rackerlabs/scantron/blob/master/initial_setup.sh 

requires root to install python3-pip. This is a problem when running as root if you plan to deploy ansible playbooks as a user. The autossh keys generated have root privs. When deploying it fails at the end with `/scantron/master/autossh.key\": Permission denied`

easy workaround is just changing autossh.key privs so the user can read, but its not an ideal situation

**Comment by derpadoo** [comment]
Tracking in https://github.com/rackerlabs/scantron/issues/42
