### ISSUE TITLE
Clarify permissions and user running initial_setup.sh in README.md

### ISSUE THREAD

**Issue by derpadoo** [rackerlabs/scantron#42]
" initial_setup.sh needs to run as root to install apt install python3-pip -y but when u run it as root u lose perms to the ssh keys generated."

**Comment by 0xtavian** [comment]
When deploying agents and masters from a ubuntu VM, initial_setup.sh executes 
`apt update`
`apt install python3-pip -y`

these require sudo privileges. 

The script goes on to install via pip which isnt recommenced to run as sudo, but more importantly the script then generate the autossh SSH key and its owned by root
`ssh-keygen -b 4096 -t rsa -f autossh -q -N ""`

When deploying ansible playbooks you'll get permission errors about unable to copy/access the key and autossh deployment will fail. 

https://pastebin.com/zpS7pt7u

**Comment by 0xtavian** [comment]
repeat issue
https://github.com/rackerlabs/scantron/issues/40

**Comment by derpadoo** [comment]
@0xtavian How about this?  Trying to keep it simple and to the point.  https://github.com/rackerlabs/scantron/pull/44/files

**Comment by 0xtavian** [comment]
@derpadoo looks good, i'll try it soon!

**Comment by derpadoo** [comment]
https://github.com/rackerlabs/scantron/pull/48
