### ISSUE TITLE
Feature Request Multiple Agents Per Site

### ISSUE THREAD

**Issue by 0xtavian** [rackerlabs/scantron#46]
As of now Scantron can only allocate one Agent per site. It would be ideal to add more than one Agent per site and have Scantron deal with the logic of splitting up the target list. 

A possible solution might be to create multiple Agents that share an API key and add "Round Robin"-type logic to delegate scan jobs to each agent.

**Comment by 0xtavian** [comment]
bump

**Comment by derpadoo** [comment]
In progress...no ETA right now.

**Comment by derpadoo** [comment]
Do you primarily use nmap or masscan?  I'll focus on result consolidation based on that.

**Comment by derpadoo** [comment]
https://github.com/rackerlabs/scantron/pull/229

![image](https://user-images.githubusercontent.com/27816854/94287456-f0f4db00-ff1b-11ea-9241-e1a8214da38b.png)
