### ISSUE TITLE
ansible-playbook crash

### ISSUE THREAD

**Issue by davidmthomsen** [rackerlabs/scantron#81]
I am get a huge error when I run the ansible-playbook
`ansible-playbook master.yml -u ubuntu --become --private-key=<agent SSH key>`

`TASK [master : Executing "/home/ubuntu/master/.venv/bin/python3.6 /home/ubuntu/master/manage.py makemigrations django_scantron" _raw_params={{ venv_python }} {{ scantron_dir }}/manage.py makemigrations {{ django_project_name }}, chdir={{ scantron_dir }}] ***
fatal: [192.168.125.137]: FAILED! => {"changed": true, "cmd": ["/home/ubuntu/master/.venv/bin/python3.6", "/home/ubuntu/master/manage.py", "makemigrations", "django_scantron"], "delta": "0:00:00.267952", "end": "2019-02-11 15:56:19.496620", "msg": "non-zero return code", "rc": 1, "start": "2019-02-11 15:56:19.228668", "stderr": "Traceback (most recent call last):\n  File \"/home/ubuntu/master/manage.py\", line 22, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 206, in fetch_command\n    klass = load_command_class(app_name, subcommand)\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 40, in load_command_class\n    module = import_module('%s.management.commands.%s' % (app_name, name))\n  File \"/home/ubuntu/master/.venv/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py\", line 12, in <module>\n    from django.db.migrations.autodetector import MigrationAutodetector\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/autodetector.py\", line 13, in <module>\n    from django.db.migrations.questioner import MigrationQuestioner\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/questioner.py\", line 12, in <module>\n    from .loader import MigrationLoader\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/loader.py\", line 10, in <module>\n    from django.db.migrations.recorder import MigrationRecorder\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/recorder.py\", line 12, in <module>\n    class MigrationRecorder(object):\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/recorder.py\", line 26, in MigrationRecorder\n    class Migration(models.Model):\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/recorder.py\", line 27, in Migration\n    app = models.CharField(max_length=255)\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py\", line 1061, in __init__\n    super(CharField, self).__init__(*args, **kwargs)\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py\", line 172, in __init__\n    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/conf/__init__.py\", line 56, in __getattr__\n    self._setup(name)\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/conf/__init__.py\", line 41, in _setup\n    self._wrapped = Settings(settings_module)\n  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/conf/__init__.py\", line 129, in __init__\n    raise ImproperlyConfigured(\"The SECRET_KEY setting must not be empty.\")\ndjango.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.", "stderr_lines": ["Traceback (most recent call last):", "  File \"/home/ubuntu/master/manage.py\", line 22, in <module>", "    execute_from_command_line(sys.argv)", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line", "    utility.execute()", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 356, in execute", "    self.fetch_command(subcommand).run_from_argv(self.argv)", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 206, in fetch_command", "    klass = load_command_class(app_name, subcommand)", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/__init__.py\", line 40, in load_command_class", "    module = import_module('%s.management.commands.%s' % (app_name, name))", "  File \"/home/ubuntu/master/.venv/lib/python3.6/importlib/__init__.py\", line 126, in import_module", "    return _bootstrap._gcd_import(name[level:], package, level)", "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import", "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load", "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked", "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked", "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module", "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py\", line 12, in <module>", "    from django.db.migrations.autodetector import MigrationAutodetector", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/autodetector.py\", line 13, in <module>", "    from django.db.migrations.questioner import MigrationQuestioner", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/questioner.py\", line 12, in <module>", "    from .loader import MigrationLoader", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/loader.py\", line 10, in <module>", "    from django.db.migrations.recorder import MigrationRecorder", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/recorder.py\", line 12, in <module>", "    class MigrationRecorder(object):", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/recorder.py\", line 26, in MigrationRecorder", "    class Migration(models.Model):", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/migrations/recorder.py\", line 27, in Migration", "    app = models.CharField(max_length=255)", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py\", line 1061, in __init__", "    super(CharField, self).__init__(*args, **kwargs)", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py\", line 172, in __init__", "    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/conf/__init__.py\", line 56, in __getattr__", "    self._setup(name)", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/conf/__init__.py\", line 41, in _setup", "    self._wrapped = Settings(settings_module)", "  File \"/home/ubuntu/master/.venv/lib/python3.6/site-packages/django/conf/__init__.py\", line 129, in __init__", "    raise ImproperlyConfigured(\"The SECRET_KEY setting must not be empty.\")", "django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty."], "stdout": "[*] Loading [ production ] scantron_secrets.json", "stdout_lines": ["[*] Loading [ production ] scantron_secrets.json"]}
	to retry, use: --limit @/home/ubuntu/Documents/scantron/ansible-playbooks/master.retry
`

**Comment by derpadoo** [comment]
Hi @davidmthomsen - thanks for submitting an issue.  Looks like the you have an empty `SECRET_KEY` value in your `master/scantron_secrets.json` file.

```
"The SECRET_KEY setting must not be empty."
```

This section should cover everything you need to do for installing Master: https://github.com/rackerlabs/scantron#master-installation

**Comment by davidmthomsen** [comment]
Thanks for responding so quickly. I generated a random string and placed it in the `master/scantron_secrets.json` file for production and got the same error. I inserted the same string for both production and local and got the same error.

**Comment by davidmthomsen** [comment]
Hey @derpadoo I got it. I needed DB Password in the `scantron_secrets.json` file.

**Comment by derpadoo** [comment]
Great!  Glad to hear it worked.  I've tried to make the install as painless as possible, but could probably do better.  Let me know if you have any other questions or issues.  Happy scanning!
