### ISSUE TITLE
WebUI Login Config

### ISSUE THREAD

**Issue by davidmthomsen** [rackerlabs/scantron#83]
Where are the credentials for the WebUI login stored?

**Comment by derpadoo** [comment]
Hi @davidmthomsen 

Default user is `admin` and the password is also set in the key `django_super_user_password` in `scantron_secrets.json` (https://github.com/rackerlabs/scantron/blob/master/master/scantron_secrets.json.empty#L2) with a minimum length of 12 (https://github.com/rackerlabs/scantron/blob/master/master/config/settings/base.py#L214)

**Comment by davidmthomsen** [comment]
For our target ranges do we have to add them all to the`master/target_files/` directory as a flat file?

**Comment by derpadoo** [comment]
Correct.  The Workflow section should help (https://github.com/rackerlabs/scantron#workflow).  So you'd create a file named something like `internal_web_servers.txt` and add the lines

```
172.16.1.20
192.168.10.0/24
192.168.11.20
192.168.20.0/25
```

the file is passed to nmap using the `-iL` switch.

**Comment by derpadoo** [comment]
Did that work for you @davidmthomsen ?  Can I close this ticket?

**Comment by derpadoo** [comment]
Going to close for now.  Just open another issue if you have any questions.

**Comment by davidmthomsen** [comment]
Actually I am still have issues. Would it be possible to set up a chat or something for this? Slack maybe?

**Comment by derpadoo** [comment]
Sure, just emailed you.
